### ISSUE TITLE
@koa/router and koa-router 8.03+ breaks segment naming for nested routes

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic-koa#35]
Breaking change: https://github.com/koajs/router/commit/fe8d745bc2f412e795f4bbc12eb71139c807ad1d

Background:

When routes from one router are leveraged by another router, the "layers" that hold onto the middleware we've instrumented get updated with the additional outer route path via Layer.setPrefix(). Our instrumentation relies on lazy-reading the layer path so that the updated name is retrieved to name middleware segments.

With `@koa/router^8.0.3` and `koa-router^8.03`, Layers are now cloned to allow for re-use / nesting in multiple routers. This change breaks our instrumentation because the original layer we have a handle on is not updated.

https://github.com/newrelic/node-newrelic-koa/blob/master/lib/router-instrumentation.js#L34

```javascript
var router2 = new Router()
router2.get('/:second', function secondMiddleware(ctx) {
  ctx.body = ' second'
})
      
router.use('/:first', router2.routes())
app.use(router.routes())
```

For the code above, secondMiddleware would previously have a segment named: `Nodejs/Middleware/Koa/secondMiddleware//:first/:second`.

Segments are now missing the `:first` nested route prefix: `Nodejs/Middleware/Koa/secondMiddleware//:second`

Unfortunately, there doesn't seem to be any obvious quick-fix with the current way the instrumentation is setup.

**Comment by michaelgoin** [comment]
size: large
