### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by jgeurts** [newrelic/node-newrelic-koa#75]
Hi, could you please push a new release to npm to get https://github.com/newrelic/node-newrelic-koa/pull/70 and https://github.com/newrelic/node-newrelic-koa/pull/72 out?

**Comment by michaelgoin** [comment]
Definitely, we'll get one out soon.

**Comment by jgeurts** [comment]
Great, thank you!

**Comment by michaelgoin** [comment]
@jgeurts i'm sure you got a bunch of pings from the attribution (sorry) but just a heads-up we've got the changes published.

v4.1.0 should be working its way through the npm caches and available shortly.

https://github.com/newrelic/node-newrelic-koa/releases/tag/v4.1.0

Thanks!
